import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'
import Experts from '../components/Experts'
import Head from 'next/head'

export default function Home() {
  return (
    <div className={styles.container}>
       <Head>
        <title>Magnolia Petcare: Experts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Experts></Experts>
      

    </div>
  )
}
